# Generated by Django 2.1.9 on 2019-09-01 09:10

from django.db import migrations, models
import mdeditor.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('image', models.ImageField(upload_to='articles_pictures/%Y/%m/%d/', verbose_name='图片')),
                ('slug', models.SlugField(max_length=255, verbose_name='url别名')),
                ('status', models.CharField(choices=[('D', '草稿'), ('P', '发布')], default='D', max_length=1, verbose_name='状态')),
                ('content', mdeditor.fields.MDTextField(verbose_name='内容')),
                ('edited', models.BooleanField(default=False, verbose_name='是否可编辑')),
                ('view_num', models.IntegerField(default=0, verbose_name='阅读数')),
                ('tags', taggit.managers.TaggableManager(help_text='多个标签，使用,隔开', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ('-created_at',),
            },
        ),
    ]
