# Generated by Django 2.1.9 on 2019-08-31 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields
import questioning.course.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uid')),
                ('title', models.CharField(default='', max_length=250, verbose_name='文章实际标题')),
                ('content', mdeditor.fields.MDTextField(verbose_name='内容')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
            },
        ),
        migrations.CreateModel(
            name='CourseChapter',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uid')),
                ('title', models.CharField(default='', max_length=250, verbose_name='章节名')),
                ('chapter_type', models.CharField(choices=[(1, '大章节'), (2, '小章节')], max_length=10, verbose_name='章节级别')),
                ('parent_chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.CourseChapter', verbose_name='父章节')),
            ],
            options={
                'verbose_name': '章节',
                'verbose_name_plural': '章节',
            },
        ),
        migrations.CreateModel(
            name='CourseName',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uid')),
                ('name', models.CharField(default='', max_length=30, verbose_name='课程名')),
                ('description', models.TextField(default='', verbose_name='类别描述')),
                ('image', models.ImageField(blank=True, null=True, upload_to=questioning.course.models.image_upload_to, verbose_name='封面图')),
            ],
            options={
                'verbose_name': '课程名',
                'verbose_name_plural': '课程名',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseChapter'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseName', verbose_name='课程名'),
        ),
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
    ]
