# Generated by Django 2.1.9 on 2019-08-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursechapter',
            name='chapter_type',
            field=models.CharField(choices=[(1, '大章节'), (2, '小章节')], default=1, max_length=10, verbose_name='章节级别'),
        ),
    ]
