# Generated by Django 2.1.9 on 2019-08-31 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20190831_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursechapter',
            name='chapter_type',
        ),
    ]
