# Generated by Django 2.1.9 on 2019-09-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_auto_20190901_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('O', '开放'), ('C', '关闭'), ('D', 'Draft')], default='O', max_length=1, verbose_name='问题状态'),
        ),
    ]
