# Generated by Django 2.1.9 on 2019-09-01 09:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDetail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('uuid_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uid')),
                ('mount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='金额变化(rmb)')),
                ('money_mount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='金额变化(金币)')),
                ('current_money', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='当前金币')),
                ('description', models.CharField(max_length=255, verbose_name='说明')),
            ],
            options={
                'verbose_name': '账户明细',
                'verbose_name_plural': '账户明细',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order_sn', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='订单号')),
                ('trade_no', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='支付流水号')),
                ('pay_status', models.CharField(choices=[('TRADE_SUCCESS', '支付成功'), ('TRADE_CLOSED', '未付款交易超时关闭'), ('WAIT_BUYER_PAY', '交易创建'), ('TRADE_FINISHED', '交易结束'), ('paying', '待支付')], default='paying', max_length=40, verbose_name='订单状态')),
                ('order_mount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='充值金额')),
                ('pay_url', models.TextField(blank=True, default='', null=True, verbose_name='支付宝支付地址')),
            ],
            options={
                'verbose_name': '充值订单',
                'verbose_name_plural': '充值订单',
            },
        ),
    ]
